#!r6rs
;; Automatically generated by private/make-aliased-libraries.sps
(library (srfi srfi-6)
  (export
    get-output-string
    open-input-string
    open-output-string)
  (import (srfi srfi-6 basic-string-ports))
)
